feat: реализовать основной функционал согласно ТЗ 11
mikkiano/java-filmorate pull request #4
Opened 2023-04-18 21:09 UTC by mikkiano

2023-04-19 19:25 UTC, mikita95 requested changes
Все сделано хорошо. Оставил лишь несколько небольших замечаний

2023-04-19 19:25 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sqlFilmsLikes = "INSERT INTO FILM_LIKE (FILM_ID, USER_ID) VALUES (?,?)";
Предполагается, что метод PUT (в данном случае addLike) должен быть идемпотентным (то есть несколько вызовов одного и того же метода с одними параметрами, имеет такой же эффект как и один вызов): https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT. В данном случае можно просто поменять sql-запрос, использовав команду merge в H2 (https://www.h2database.com/html/commands.html#merge_into) - если запись существует, то это сработает как update, иначе произойдет insert.
Конечно, понятие идемпотентности предполагает в большей степени именно влияние на состояние сервера, а не клиента, и в данном случае состояние не изменится (так как данные не поменяются). Но с точки зрение клиента - это не ошибка, поставить повторно лайк фильму.
В таком случае нужно также и поменять запрос обновления rate, лучше сетить ему значение равное количеству лайков, а не просто +1.

2023-04-19 19:25 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sqlFilms = "UPDATE FILM SET RATE = RATE - 1 WHERE ID = ?";
Если вызвать удаление несколько раз, то rate может стать отрицательным.
Лучше сетить ему значение равное количеству лайков, а не просто +1.

2023-04-19 19:25 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                .mpa(mpaStorage.getMpaById(resultSet.getInt("MPA_ID")).orElseThrow(ValidationException::new))
Здесь вы делаете лишний запрос по сути. Можно получить mpa сразу вместе с фильмом, cджойнив таблицу film с таблицей mpa

2023-04-19 19:25 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +            String friendAccept = "INSERT INTO USER_FRIEND (USER_ID, FRIEND_ID, IS_ACCEPTED) VALUES (?, ?, 'true')";
Если попытаться несколько раз добавить одного друга, то здесь будет ошибка, лучше использовать оператор merge, чтобы учесть, что запись уже есть и ошибки бы не было

2023-04-19 20:27 UTC, mikkiano commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sqlFilmsLikes = "INSERT INTO FILM_LIKE (FILM_ID, USER_ID) VALUES (?,?)";
Если поменять запрос обновления rate, то перестанет проходить тест like/Film most popular film.
В тесте "film/Film id=2 create" создаётся новый фильм со значением rate = 4, при проставлении лайка тестом "like/Film id=2 add Like from user id=1", значение rate становится равным 1, т.к. нет записей лайков в таблице FILM_LIKE.

2023-04-20 15:06 UTC, mikita95 approved these changes
Все сделано отлично. Можно мержить пул-реквест

2023-04-20 15:08 UTC, merged